### ISSUE TITLE
Cellbender error caused by checkpoint file ckpt.tar.gz

### ISSUE THREAD

**Issue by yuhsinhsieh-josch** [cfusterot/multiSAP#3]
When running multiple cellbender jobs from the same directory (multiSAP in our case), ckpt.tar.gz was being overwritten by different jobs, therefore causing an error. 

[cellbender issue page about checkpoint](https://github.com/broadinstitute/CellBender/issues/241)
[example log file from us: cellbender-1142095.log](https://github.com/cfusterot/multiSAP/files/13256382/cellbender-1142095.log)

We need to find a way to run this Cellbender in separate subfolders...
(didn't realized it because previously gpu was so heavily occupied lol)

**Comment by yuhsinhsieh-josch** [comment]
Change the `shell` in ` rules/cellbender.smk`

>  26         shell:
 27             """
 28             cd {OUTDIR}/{wildcards.sample}
 29             cellbender remove-background --input {params.h5} --output {output.cb} --fpr {params.fpr} --cuda --epochs {params.epochs} --expected-cells {par    ams.expected_cells} --learning-rate {params.learning_rate} {params.extra}
 30             mv ckpt.tar.gz {OUTDIR}/{wildcards.sample}/cellbender
 31             """
 
 Hope this will do the job lol, will let you know

P.s. in the cellbender commend it add additional flag --learning-rate {params.learning_rate}, and thus in the `Sankefile`, i added one parameter:

> cellbender:
  enable: TRUE
  params:
    fpr: 0.01
    epochs: 150
    expected_cells: 15000
    learning_rate: 5e-5 #default 1e-4
    extra: "--exclude-feature-types Peaks"

**Comment by yuhsinhsieh-josch** [comment]
Solved 🥳

**Comment by cfusterot** [comment]
Just added these modifications in the latest commit #11487cf04b26613efd1d14b7a7fc55d0c446c5a1
